name: Create Debian package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: install devscripts
      run: sudo apt-get install --no-install-recommends devscripts equivs
      
    - name: mk-build-deps
      run: mk-build-deps --root-cmd sudo --install --tool "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"

    - name: Build Debian package
      run: ./autogen.sh && dpkg-buildpackage -b -us -uc

    - name: Move deb packages
      run: mkdir packages && mv ../*.deb packages/
      
    - uses: actions/upload-artifact@v1
      with:
        name: Debian packages
        path: packages
